version: "3.9"

services:
  meetup-api:
    container_name: meetup-api
    depends_on:
      - postgres
    ports:
      - "${APP_PORT}:8080"
    build:
      context: .
    environment:
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:?dbUserNameNorProvided}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:?dbPasswordNotProvided}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: 'postgres:13.1-alpine'
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped